# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/ksalone/Loitsut/red-pitaya-notes/cfg/clocks.xdc

# XDC: /home/ksalone/Loitsut/red-pitaya-notes/cfg/ports.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_pll_0_0/system_pll_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_pll_0_0 || ORIG_REF_NAME==system_pll_0_0} -quiet] -quiet

# IP: bd/system/ip/system_ps_0_0/system_ps_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps_0_0 || ORIG_REF_NAME==system_ps_0_0} -quiet] -quiet

# IP: bd/system/ip/system_const_0_0/system_const_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_const_0_0 || ORIG_REF_NAME==system_const_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_0_0/system_rst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_0_0 || ORIG_REF_NAME==system_rst_0_0} -quiet] -quiet

# IP: bd/system/ip/system_adc_0_0/system_adc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_adc_0_0 || ORIG_REF_NAME==system_adc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_dac_0_0/system_dac_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dac_0_0 || ORIG_REF_NAME==system_dac_0_0} -quiet] -quiet

# IP: bd/system/ip/system_hub_0_0/system_hub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_hub_0_0 || ORIG_REF_NAME==system_hub_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_slice_0_0/system_rst_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_slice_0_0 || ORIG_REF_NAME==system_rst_slice_0_0} -quiet] -quiet

# IP: bd/system/ip/system_sel_slice_0_0/system_sel_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sel_slice_0_0 || ORIG_REF_NAME==system_sel_slice_0_0} -quiet] -quiet

# IP: bd/system/ip/system_neg_slice_0_0/system_neg_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_neg_slice_0_0 || ORIG_REF_NAME==system_neg_slice_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_slice_1_0/system_rst_slice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_slice_1_0 || ORIG_REF_NAME==system_rst_slice_1_0} -quiet] -quiet

# IP: bd/system/ip/system_neg_slice_1_0/system_neg_slice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_neg_slice_1_0 || ORIG_REF_NAME==system_neg_slice_1_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_slice_2_0/system_rst_slice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_slice_2_0 || ORIG_REF_NAME==system_rst_slice_2_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_slice_3_0/system_rst_slice_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_slice_3_0 || ORIG_REF_NAME==system_rst_slice_3_0} -quiet] -quiet

# IP: bd/system/ip/system_sel_slice_1_0/system_sel_slice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sel_slice_1_0 || ORIG_REF_NAME==system_sel_slice_1_0} -quiet] -quiet

# IP: bd/system/ip/system_neg_slice_2_0/system_neg_slice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_neg_slice_2_0 || ORIG_REF_NAME==system_neg_slice_2_0} -quiet] -quiet

# IP: bd/system/ip/system_neg_slice_3_0/system_neg_slice_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_neg_slice_3_0 || ORIG_REF_NAME==system_neg_slice_3_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_slice_4_0/system_rst_slice_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_slice_4_0 || ORIG_REF_NAME==system_rst_slice_4_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_slice_5_0/system_rst_slice_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_slice_5_0 || ORIG_REF_NAME==system_rst_slice_5_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_0_0/system_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_0_0 || ORIG_REF_NAME==system_slice_0_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_1_0/system_slice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_1_0 || ORIG_REF_NAME==system_slice_1_0} -quiet] -quiet

# IP: bd/system/ip/system_cfg_slice_0_0/system_cfg_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cfg_slice_0_0 || ORIG_REF_NAME==system_cfg_slice_0_0} -quiet] -quiet

# IP: bd/system/ip/system_cfg_slice_1_0/system_cfg_slice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cfg_slice_1_0 || ORIG_REF_NAME==system_cfg_slice_1_0} -quiet] -quiet

# IP: bd/system/ip/system_cfg_slice_2_0/system_cfg_slice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cfg_slice_2_0 || ORIG_REF_NAME==system_cfg_slice_2_0} -quiet] -quiet

# IP: bd/system/ip/system_cfg_slice_3_0/system_cfg_slice_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cfg_slice_3_0 || ORIG_REF_NAME==system_cfg_slice_3_0} -quiet] -quiet

# IP: bd/system/ip/system_cfg_slice_4_0/system_cfg_slice_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cfg_slice_4_0 || ORIG_REF_NAME==system_cfg_slice_4_0} -quiet] -quiet

# IP: bd/system/ip/system_cfg_slice_5_0/system_cfg_slice_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cfg_slice_5_0 || ORIG_REF_NAME==system_cfg_slice_5_0} -quiet] -quiet

# IP: bd/system/ip/system_bcast_0_0/system_bcast_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bcast_0_0 || ORIG_REF_NAME==system_bcast_0_0} -quiet] -quiet

# IP: bd/system/ip/system_neg_0_0/system_neg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_neg_0_0 || ORIG_REF_NAME==system_neg_0_0} -quiet] -quiet

# IP: bd/system/ip/system_neg_1_0/system_neg_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_neg_1_0 || ORIG_REF_NAME==system_neg_1_0} -quiet] -quiet

# IP: bd/system/ip/system_neg_2_0/system_neg_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_neg_2_0 || ORIG_REF_NAME==system_neg_2_0} -quiet] -quiet

# IP: bd/system/ip/system_neg_3_0/system_neg_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_neg_3_0 || ORIG_REF_NAME==system_neg_3_0} -quiet] -quiet

# IP: bd/system/ip/system_neg_4_0/system_neg_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_neg_4_0 || ORIG_REF_NAME==system_neg_4_0} -quiet] -quiet

# IP: bd/system/ip/system_neg_5_0/system_neg_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_neg_5_0 || ORIG_REF_NAME==system_neg_5_0} -quiet] -quiet

# IP: bd/system/ip/system_neg_6_0/system_neg_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_neg_6_0 || ORIG_REF_NAME==system_neg_6_0} -quiet] -quiet

# IP: bd/system/ip/system_neg_7_0/system_neg_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_neg_7_0 || ORIG_REF_NAME==system_neg_7_0} -quiet] -quiet

# IP: bd/system/ip/system_rate_0_0/system_rate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rate_0_0 || ORIG_REF_NAME==system_rate_0_0} -quiet] -quiet

# IP: bd/system/ip/system_cic_0_0/system_cic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cic_0_0 || ORIG_REF_NAME==system_cic_0_0} -quiet] -quiet

# IP: bd/system/ip/system_sel_0_0/system_sel_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sel_0_0 || ORIG_REF_NAME==system_sel_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rate_1_0/system_rate_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rate_1_0 || ORIG_REF_NAME==system_rate_1_0} -quiet] -quiet

# IP: bd/system/ip/system_cic_1_0/system_cic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cic_1_0 || ORIG_REF_NAME==system_cic_1_0} -quiet] -quiet

# IP: bd/system/ip/system_sel_1_0/system_sel_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sel_1_0 || ORIG_REF_NAME==system_sel_1_0} -quiet] -quiet

# IP: bd/system/ip/system_rate_2_0/system_rate_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rate_2_0 || ORIG_REF_NAME==system_rate_2_0} -quiet] -quiet

# IP: bd/system/ip/system_cic_2_0/system_cic_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cic_2_0 || ORIG_REF_NAME==system_cic_2_0} -quiet] -quiet

# IP: bd/system/ip/system_sel_2_0/system_sel_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sel_2_0 || ORIG_REF_NAME==system_sel_2_0} -quiet] -quiet

# IP: bd/system/ip/system_rate_3_0/system_rate_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rate_3_0 || ORIG_REF_NAME==system_rate_3_0} -quiet] -quiet

# IP: bd/system/ip/system_cic_3_0/system_cic_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cic_3_0 || ORIG_REF_NAME==system_cic_3_0} -quiet] -quiet

# IP: bd/system/ip/system_sel_3_0/system_sel_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sel_3_0 || ORIG_REF_NAME==system_sel_3_0} -quiet] -quiet

# IP: bd/system/ip/system_comb_0_0/system_comb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_comb_0_0 || ORIG_REF_NAME==system_comb_0_0} -quiet] -quiet

# IP: bd/system/ip/system_fir_0_0/system_fir_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fir_0_0 || ORIG_REF_NAME==system_fir_0_0} -quiet] -quiet

# IP: bd/system/ip/system_comb_1_0/system_comb_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_comb_1_0 || ORIG_REF_NAME==system_comb_1_0} -quiet] -quiet

# IP: bd/system/ip/system_fir_1_0/system_fir_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fir_1_0 || ORIG_REF_NAME==system_fir_1_0} -quiet] -quiet

# IP: bd/system/ip/system_bcast_1_0/system_bcast_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bcast_1_0 || ORIG_REF_NAME==system_bcast_1_0} -quiet] -quiet

# IP: bd/system/ip/system_bcast_2_0/system_bcast_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bcast_2_0 || ORIG_REF_NAME==system_bcast_2_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_0_1/system_slice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_0_1 || ORIG_REF_NAME==system_slice_0_1} -quiet] -quiet

# IP: bd/system/ip/system_slice_1_1/system_slice_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_1_1 || ORIG_REF_NAME==system_slice_1_1} -quiet] -quiet

# IP: bd/system/ip/system_slice_2_0/system_slice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_2_0 || ORIG_REF_NAME==system_slice_2_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_3_0/system_slice_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_3_0 || ORIG_REF_NAME==system_slice_3_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_4_0/system_slice_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_4_0 || ORIG_REF_NAME==system_slice_4_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_5_0/system_slice_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_5_0 || ORIG_REF_NAME==system_slice_5_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_6_0/system_slice_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_6_0 || ORIG_REF_NAME==system_slice_6_0} -quiet] -quiet

# IP: bd/system/ip/system_timer_0_0/system_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_timer_0_0 || ORIG_REF_NAME==system_timer_0_0} -quiet] -quiet

# IP: bd/system/ip/system_pha_0_0/system_pha_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_pha_0_0 || ORIG_REF_NAME==system_pha_0_0} -quiet] -quiet

# IP: bd/system/ip/system_vldtr_0_0/system_vldtr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_vldtr_0_0 || ORIG_REF_NAME==system_vldtr_0_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_0_2/system_slice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_0_2 || ORIG_REF_NAME==system_slice_0_2} -quiet] -quiet

# IP: bd/system/ip/system_bram_0_0/system_bram_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bram_0_0 || ORIG_REF_NAME==system_bram_0_0} -quiet] -quiet

# IP: bd/system/ip/system_hst_0_0/system_hst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_hst_0_0 || ORIG_REF_NAME==system_hst_0_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_0_3/system_slice_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_0_3 || ORIG_REF_NAME==system_slice_0_3} -quiet] -quiet

# IP: bd/system/ip/system_slice_1_2/system_slice_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_1_2 || ORIG_REF_NAME==system_slice_1_2} -quiet] -quiet

# IP: bd/system/ip/system_slice_2_1/system_slice_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_2_1 || ORIG_REF_NAME==system_slice_2_1} -quiet] -quiet

# IP: bd/system/ip/system_slice_3_1/system_slice_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_3_1 || ORIG_REF_NAME==system_slice_3_1} -quiet] -quiet

# IP: bd/system/ip/system_slice_4_1/system_slice_4_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_4_1 || ORIG_REF_NAME==system_slice_4_1} -quiet] -quiet

# IP: bd/system/ip/system_slice_5_1/system_slice_5_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_5_1 || ORIG_REF_NAME==system_slice_5_1} -quiet] -quiet

# IP: bd/system/ip/system_slice_6_1/system_slice_6_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_6_1 || ORIG_REF_NAME==system_slice_6_1} -quiet] -quiet

# IP: bd/system/ip/system_timer_0_1/system_timer_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_timer_0_1 || ORIG_REF_NAME==system_timer_0_1} -quiet] -quiet

# IP: bd/system/ip/system_pha_0_1/system_pha_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_pha_0_1 || ORIG_REF_NAME==system_pha_0_1} -quiet] -quiet

# IP: bd/system/ip/system_vldtr_0_1/system_vldtr_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_vldtr_0_1 || ORIG_REF_NAME==system_vldtr_0_1} -quiet] -quiet

# IP: bd/system/ip/system_slice_0_4/system_slice_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_0_4 || ORIG_REF_NAME==system_slice_0_4} -quiet] -quiet

# IP: bd/system/ip/system_bram_0_1/system_bram_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bram_0_1 || ORIG_REF_NAME==system_bram_0_1} -quiet] -quiet

# IP: bd/system/ip/system_hst_0_1/system_hst_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_hst_0_1 || ORIG_REF_NAME==system_hst_0_1} -quiet] -quiet

# IP: bd/system/ip/system_slice_0_5/system_slice_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_0_5 || ORIG_REF_NAME==system_slice_0_5} -quiet] -quiet

# IP: bd/system/ip/system_slice_1_3/system_slice_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_1_3 || ORIG_REF_NAME==system_slice_1_3} -quiet] -quiet

# IP: bd/system/ip/system_slice_2_2/system_slice_2_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_2_2 || ORIG_REF_NAME==system_slice_2_2} -quiet] -quiet

# IP: bd/system/ip/system_slice_3_2/system_slice_3_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_3_2 || ORIG_REF_NAME==system_slice_3_2} -quiet] -quiet

# IP: bd/system/ip/system_slice_4_2/system_slice_4_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_4_2 || ORIG_REF_NAME==system_slice_4_2} -quiet] -quiet

# IP: bd/system/ip/system_slice_5_2/system_slice_5_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_5_2 || ORIG_REF_NAME==system_slice_5_2} -quiet] -quiet

# IP: bd/system/ip/system_slice_6_2/system_slice_6_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_6_2 || ORIG_REF_NAME==system_slice_6_2} -quiet] -quiet

# IP: bd/system/ip/system_slice_7_0/system_slice_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_7_0 || ORIG_REF_NAME==system_slice_7_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_8_0/system_slice_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_8_0 || ORIG_REF_NAME==system_slice_8_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_9_0/system_slice_9_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_9_0 || ORIG_REF_NAME==system_slice_9_0} -quiet] -quiet

# IP: bd/system/ip/system_sel_0_1/system_sel_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sel_0_1 || ORIG_REF_NAME==system_sel_0_1} -quiet] -quiet

# IP: bd/system/ip/system_const_0_1/system_const_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_const_0_1 || ORIG_REF_NAME==system_const_0_1} -quiet] -quiet

# IP: bd/system/ip/system_trig_0_0/system_trig_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_trig_0_0 || ORIG_REF_NAME==system_trig_0_0} -quiet] -quiet

# IP: bd/system/ip/system_or_0_0/system_or_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_or_0_0 || ORIG_REF_NAME==system_or_0_0} -quiet] -quiet

# IP: bd/system/ip/system_comb_0_1/system_comb_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_comb_0_1 || ORIG_REF_NAME==system_comb_0_1} -quiet] -quiet

# IP: bd/system/ip/system_scope_0_0/system_scope_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_scope_0_0 || ORIG_REF_NAME==system_scope_0_0} -quiet] -quiet

# IP: bd/system/ip/system_const_1_0/system_const_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_const_1_0 || ORIG_REF_NAME==system_const_1_0} -quiet] -quiet

# IP: bd/system/ip/system_writer_0_0/system_writer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_writer_0_0 || ORIG_REF_NAME==system_writer_0_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_0_6/system_slice_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_0_6 || ORIG_REF_NAME==system_slice_0_6} -quiet] -quiet

# IP: bd/system/ip/system_slice_1_4/system_slice_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_1_4 || ORIG_REF_NAME==system_slice_1_4} -quiet] -quiet

# IP: bd/system/ip/system_slice_2_3/system_slice_2_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_2_3 || ORIG_REF_NAME==system_slice_2_3} -quiet] -quiet

# IP: bd/system/ip/system_slice_3_3/system_slice_3_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_3_3 || ORIG_REF_NAME==system_slice_3_3} -quiet] -quiet

# IP: bd/system/ip/system_slice_4_3/system_slice_4_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_4_3 || ORIG_REF_NAME==system_slice_4_3} -quiet] -quiet

# IP: bd/system/ip/system_slice_5_3/system_slice_5_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_5_3 || ORIG_REF_NAME==system_slice_5_3} -quiet] -quiet

# IP: bd/system/ip/system_slice_6_3/system_slice_6_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_6_3 || ORIG_REF_NAME==system_slice_6_3} -quiet] -quiet

# IP: bd/system/ip/system_timer_0_2/system_timer_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_timer_0_2 || ORIG_REF_NAME==system_timer_0_2} -quiet] -quiet

# IP: bd/system/ip/system_pha_0_2/system_pha_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_pha_0_2 || ORIG_REF_NAME==system_pha_0_2} -quiet] -quiet

# IP: bd/system/ip/system_vldtr_0_2/system_vldtr_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_vldtr_0_2 || ORIG_REF_NAME==system_vldtr_0_2} -quiet] -quiet

# IP: bd/system/ip/system_slice_0_7/system_slice_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_0_7 || ORIG_REF_NAME==system_slice_0_7} -quiet] -quiet

# IP: bd/system/ip/system_slice_1_5/system_slice_1_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_1_5 || ORIG_REF_NAME==system_slice_1_5} -quiet] -quiet

# IP: bd/system/ip/system_slice_2_4/system_slice_2_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_2_4 || ORIG_REF_NAME==system_slice_2_4} -quiet] -quiet

# IP: bd/system/ip/system_slice_3_4/system_slice_3_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_3_4 || ORIG_REF_NAME==system_slice_3_4} -quiet] -quiet

# IP: bd/system/ip/system_slice_4_4/system_slice_4_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_4_4 || ORIG_REF_NAME==system_slice_4_4} -quiet] -quiet

# IP: bd/system/ip/system_slice_5_4/system_slice_5_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_5_4 || ORIG_REF_NAME==system_slice_5_4} -quiet] -quiet

# IP: bd/system/ip/system_slice_6_4/system_slice_6_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_6_4 || ORIG_REF_NAME==system_slice_6_4} -quiet] -quiet

# IP: bd/system/ip/system_timer_0_3/system_timer_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_timer_0_3 || ORIG_REF_NAME==system_timer_0_3} -quiet] -quiet

# IP: bd/system/ip/system_pha_0_3/system_pha_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_pha_0_3 || ORIG_REF_NAME==system_pha_0_3} -quiet] -quiet

# IP: bd/system/ip/system_vldtr_0_3/system_vldtr_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_vldtr_0_3 || ORIG_REF_NAME==system_vldtr_0_3} -quiet] -quiet

# IP: bd/system/ip/system_slice_2_5/system_slice_2_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_2_5 || ORIG_REF_NAME==system_slice_2_5} -quiet] -quiet

# IP: bd/system/ip/system_slice_3_5/system_slice_3_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_3_5 || ORIG_REF_NAME==system_slice_3_5} -quiet] -quiet

# IP: bd/system/ip/system_concat_0_0/system_concat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_concat_0_0 || ORIG_REF_NAME==system_concat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_or_0_1/system_or_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_or_0_1 || ORIG_REF_NAME==system_or_0_1} -quiet] -quiet

# IP: bd/system/ip/system_fifo_0_0/system_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fifo_0_0 || ORIG_REF_NAME==system_fifo_0_0} -quiet] -quiet

# IP: bd/system/ip/system_slice_0_8/system_slice_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_0_8 || ORIG_REF_NAME==system_slice_0_8} -quiet] -quiet

# IP: bd/system/ip/system_slice_1_6/system_slice_1_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_slice_1_6 || ORIG_REF_NAME==system_slice_1_6} -quiet] -quiet

# IP: bd/system/ip/system_fifo_0_1/system_fifo_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fifo_0_1 || ORIG_REF_NAME==system_fifo_0_1} -quiet] -quiet

# IP: bd/system/ip/system_gen_0_0/system_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gen_0_0 || ORIG_REF_NAME==system_gen_0_0} -quiet] -quiet

# IP: bd/system/ip/system_zeroer_0_0/system_zeroer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_zeroer_0_0 || ORIG_REF_NAME==system_zeroer_0_0} -quiet] -quiet

# IP: bd/system/ip/system_iir_0_0/system_iir_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_iir_0_0 || ORIG_REF_NAME==system_iir_0_0} -quiet] -quiet

# IP: bd/system/ip/system_concat_1_0/system_concat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_concat_1_0 || ORIG_REF_NAME==system_concat_1_0} -quiet] -quiet

# XDC: /home/ksalone/Loitsut/red-pitaya-notes/tmp/mcpha.gen/sources_1/bd/system/ip/system_pll_0_0/system_pll_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_pll_0_0 || ORIG_REF_NAME==system_pll_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ksalone/Loitsut/red-pitaya-notes/tmp/mcpha.gen/sources_1/bd/system/ip/system_pll_0_0/system_pll_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_pll_0_0 || ORIG_REF_NAME==system_pll_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ksalone/Loitsut/red-pitaya-notes/tmp/mcpha.gen/sources_1/bd/system/ip/system_pll_0_0/system_pll_0_0_ooc.xdc

# XDC: /home/ksalone/Loitsut/red-pitaya-notes/tmp/mcpha.gen/sources_1/bd/system/ip/system_ps_0_0/system_ps_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ps_0_0 || ORIG_REF_NAME==system_ps_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ksalone/Loitsut/red-pitaya-notes/tmp/mcpha.gen/sources_1/bd/system/ip/system_rst_0_0/system_rst_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_0_0 || ORIG_REF_NAME==system_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ksalone/Loitsut/red-pitaya-notes/tmp/mcpha.gen/sources_1/bd/system/ip/system_rst_0_0/system_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_0_0 || ORIG_REF_NAME==system_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ksalone/Loitsut/red-pitaya-notes/tmp/mcpha.gen/sources_1/bd/system/ip/system_bcast_0_0/system_bcast_0_0_ooc.xdc

# XDC: /home/ksalone/Loitsut/red-pitaya-notes/tmp/mcpha.gen/sources_1/bd/system/ip/system_fir_0_0/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fir_0_0 || ORIG_REF_NAME==system_fir_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ksalone/Loitsut/red-pitaya-notes/tmp/mcpha.gen/sources_1/bd/system/ip/system_fir_1_0/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fir_1_0 || ORIG_REF_NAME==system_fir_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ksalone/Loitsut/red-pitaya-notes/tmp/mcpha.gen/sources_1/bd/system/ip/system_bcast_1_0/system_bcast_1_0_ooc.xdc

# XDC: /home/ksalone/Loitsut/red-pitaya-notes/tmp/mcpha.gen/sources_1/bd/system/ip/system_bcast_2_0/system_bcast_2_0_ooc.xdc

# XDC: /home/ksalone/Loitsut/red-pitaya-notes/tmp/mcpha.gen/sources_1/bd/system/ip/system_bram_0_0/system_bram_0_0_ooc.xdc

# XDC: /home/ksalone/Loitsut/red-pitaya-notes/tmp/mcpha.gen/sources_1/bd/system/ip/system_bram_0_1/system_bram_0_1_ooc.xdc

# XDC: /home/ksalone/Loitsut/red-pitaya-notes/tmp/mcpha.gen/sources_1/bd/system/ip/system_comb_0_1/system_comb_0_1_ooc.xdc

# XDC: /home/ksalone/Loitsut/red-pitaya-notes/tmp/mcpha.gen/sources_1/bd/system/system_ooc.xdc
